---
engines:
  brakeman:
    enabled: true
    checks:
      dangerous_attr_accessible:
        enabled: false
    exclude_fingerprints:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: .codeclimate_rubocop.yml
ratings:
  paths:
  - Gemfile.lock
  - '**.erb'
  - '**.haml'
  - '**.rb'
  - '**.rhtml'
  - '**.slim'
  - '**.css'
  - '**.coffee'
  - '**.inc'
  - '**.js'
  - '**.jsx'
  - '**.module'
  - '**.php'
  - '**.py'
exclude_paths:
- config/
- db/
- lib/tasks/
- script/
- spec/
- vendor/
- public/
prepare:
  fetch:
  - url: 'https://raw.githubusercontent.com/hintmedia/hint-rubocop_style/master/default.yml'
    path: 'default.yml'
