default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: <%= ENV.fetch('DB_USERNAME', 'dinjas') %>
  password: <%= ENV.fetch("DB_PASSWORD", '') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dewts_development

test:
  <<: *default
  database: dewts_test

production:
  <<: *default
  database: dewts_production
