default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: <%= ENV.fetch('DB_USERNAME', 'dinjas') %>
  password: <%= ENV.fetch("DB_PASSWORD", '') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME', 'dewts')}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME', 'dewts')}_test" %>

production:
  <<: *default
  database: <%= "#{ENV.fetch('APP_NAME', 'dewts')}_production" %>
